-- Sequências necessárias (criadas antes das tabelas)
CREATE SEQUENCE IF NOT EXISTS perfil_id_perfil_seq;
CREATE SEQUENCE IF NOT EXISTS produto_id_produto_seq;
CREATE SEQUENCE IF NOT EXISTS usuario_id_usuario_seq;
CREATE SEQUENCE IF NOT EXISTS lote_id_lote_seq;
CREATE SEQUENCE IF NOT EXISTS pacote_id_pacote_seq;
CREATE SEQUENCE IF NOT EXISTS rfid_etiqueta_id_rfid_seq;
CREATE SEQUENCE IF NOT EXISTS movimentacao_estoque_id_movimentacao_seq;
CREATE SEQUENCE IF NOT EXISTS alerta_id_alerta_seq;
CREATE SEQUENCE IF NOT EXISTS relatorio_id_relatorio_seq;
CREATE SEQUENCE IF NOT EXISTS sugestao_reposicao_id_sugestao_seq;
-- leitura_rfid_raw usa bigserial (sequência gerada automaticamente)
-- leitor_rfid usa GENERATED BY DEFAULT AS IDENTITY (sequência gerada automaticamente)

-- 1. Tabelas Independentes (Sem chaves estrangeiras)
CREATE TABLE public.perfil (
  id_perfil integer NOT NULL DEFAULT nextval('perfil_id_perfil_seq'::regclass),
  nome character varying NOT NULL,
  descricao text,
  CONSTRAINT perfil_pkey PRIMARY KEY (id_perfil)
);

CREATE TABLE public.produto (
  id_produto integer NOT NULL DEFAULT nextval('produto_id_produto_seq'::regclass),
  nome character varying NOT NULL,
  descricao text,
  estoque_minimo integer NOT NULL,
  CONSTRAINT produto_pkey PRIMARY KEY (id_produto)
);

-- NOVA TABELA: Mapeamento do Hardware RFID (Antenas/Portais)
CREATE TABLE public.leitor_rfid (
  id_leitor integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  codigo_equipamento character varying NOT NULL UNIQUE,
  localizacao character varying NOT NULL,
  status character varying DEFAULT 'ATIVO',
  CONSTRAINT leitor_rfid_pkey PRIMARY KEY (id_leitor)
);

-- 2. Tabelas com Dependências Nível 1
CREATE TABLE public.usuario (
  id_usuario integer NOT NULL DEFAULT nextval('usuario_id_usuario_seq'::regclass),
  nome character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  senha text NOT NULL,
  id_perfil integer NOT NULL,
  CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario),
  CONSTRAINT fk_usuario_perfil FOREIGN KEY (id_perfil) REFERENCES public.perfil(id_perfil)
);

CREATE TABLE public.lote (
  id_lote integer NOT NULL DEFAULT nextval('lote_id_lote_seq'::regclass),
  codigo_lote character varying NOT NULL,
  data_fabricacao date,
  data_validade date,
  status character varying,
  id_produto integer NOT NULL,
  CONSTRAINT lote_pkey PRIMARY KEY (id_lote),
  CONSTRAINT fk_lote_produto FOREIGN KEY (id_produto) REFERENCES public.produto(id_produto)
);

CREATE TABLE public.sugestao_reposicao (
  id_sugestao integer NOT NULL DEFAULT nextval('sugestao_reposicao_id_sugestao_seq'::regclass),
  data_sugestao timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  quantidade_sugerida integer NOT NULL,
  id_produto integer NOT NULL,
  CONSTRAINT sugestao_reposicao_pkey PRIMARY KEY (id_sugestao),
  CONSTRAINT fk_sugestao_produto FOREIGN KEY (id_produto) REFERENCES public.produto(id_produto)
);

-- 3. Tabelas com Dependências Nível 2
CREATE TABLE public.pacote (
  id_pacote integer NOT NULL DEFAULT nextval('pacote_id_pacote_seq'::regclass),
  id_lote integer NOT NULL,
  CONSTRAINT pacote_pkey PRIMARY KEY (id_pacote),
  CONSTRAINT fk_pacote_lote FOREIGN KEY (id_lote) REFERENCES public.lote(id_lote)
);

CREATE TABLE public.alerta (
  id_alerta integer NOT NULL DEFAULT nextval('alerta_id_alerta_seq'::regclass),
  tipo_alerta character varying NOT NULL,
  mensagem text,
  data_hora timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_lote integer NOT NULL,
  CONSTRAINT alerta_pkey PRIMARY KEY (id_alerta),
  CONSTRAINT fk_alerta_lote FOREIGN KEY (id_lote) REFERENCES public.lote(id_lote)
);

CREATE TABLE public.relatorio (
  id_relatorio integer NOT NULL DEFAULT nextval('relatorio_id_relatorio_seq'::regclass),
  tipo_relatorio character varying,
  data_geracao timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_usuario integer NOT NULL,
  CONSTRAINT relatorio_pkey PRIMARY KEY (id_relatorio),
  CONSTRAINT fk_relatorio_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario)
);

-- NOVA TABELA: Log Bruto de Leituras RFID (Para processamento em massa)
CREATE TABLE public.leitura_rfid_raw (
  id_leitura bigserial PRIMARY KEY,
  epc character varying NOT NULL,
  id_leitor integer NOT NULL,
  data_hora timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rssi integer, 
  CONSTRAINT fk_leitura_raw_leitor FOREIGN KEY (id_leitor) REFERENCES public.leitor_rfid(id_leitor)
);

-- 4. Tabelas com Dependências Nível 3 (Atualizadas para RFID)

-- TABELA ATUALIZADA: Adequação para padrão EPC e controle de ciclo de vida
CREATE TABLE public.rfid_etiqueta (
  id_rfid integer NOT NULL DEFAULT nextval('rfid_etiqueta_id_rfid_seq'::regclass),
  epc character varying NOT NULL UNIQUE, -- Antigo codigo_rfid
  id_pacote integer NOT NULL UNIQUE,
  status character varying DEFAULT 'ATIVO',
  data_associacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT rfid_etiqueta_pkey PRIMARY KEY (id_rfid),
  CONSTRAINT fk_rfid_pacote FOREIGN KEY (id_pacote) REFERENCES public.pacote(id_pacote)
);

-- TABELA ATUALIZADA: Vinculada ao leitor de hardware; id_usuario opcional
CREATE TABLE public.movimentacao_estoque (
  id_movimentacao integer NOT NULL DEFAULT nextval('movimentacao_estoque_id_movimentacao_seq'::regclass),
  tipo_movimentacao character varying NOT NULL,
  data_hora timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_leitor integer, -- Substitui a origem_leitura manual
  id_pacote integer NOT NULL,
  id_usuario integer, -- Removido o NOT NULL
  CONSTRAINT movimentacao_estoque_pkey PRIMARY KEY (id_movimentacao),
  CONSTRAINT fk_movimentacao_pacote FOREIGN KEY (id_pacote) REFERENCES public.pacote(id_pacote),
  CONSTRAINT fk_movimentacao_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario),
  CONSTRAINT fk_movimentacao_leitor FOREIGN KEY (id_leitor) REFERENCES public.leitor_rfid(id_leitor)
);